sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8

install: mvn install -T 2.5C -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
    - mvn test --projects "$MODULE" -Dtest=$TESTS -DfailIfNoTests=false
