package com.github.fppt.jedismock.processor;

import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.CodeBlock;
import com.palantir.javapoet.FieldSpec;
import com.palantir.javapoet.JavaFile;
import com.palantir.javapoet.MethodSpec;
import com.palantir.javapoet.ParameterizedTypeName;
import com.palantir.javapoet.TypeName;
import com.palantir.javapoet.TypeSpec;
import com.palantir.javapoet.WildcardTypeName;

import javax.annotation.processing.AbstractProcessor;
import javax.annotation.processing.RoundEnvironment;
import javax.annotation.processing.SupportedAnnotationTypes;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.AnnotationMirror;
import javax.lang.model.element.AnnotationValue;
import javax.lang.model.element.Element;
import javax.lang.model.element.ElementKind;
import javax.lang.model.element.ExecutableElement;
import javax.lang.model.element.Modifier;
import javax.lang.model.element.TypeElement;
import javax.lang.model.type.TypeMirror;
import javax.tools.Diagnostic;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import java.util.SortedMap;
import java.util.TreeMap;

/**
 * Generates, at compile time, the lookup table that {@code CommandFactory} uses
 * to find the operation class behind a Redis command name.
 *
 * <p>Every class carrying {@code @RedisCommand} is reported to this processor by
 * javac, so the commands are located by the compiler rather than by scanning the
 * classpath at start-up. The processor emits a single {@code CommandRegistries}
 * class in {@code com.github.fppt.jedismock.operations}, holding the whole command
 * table in a hard-coded static initializer.
 *
 * <p>Operations are named by their binary name and loaded with
 * {@link Class#forName(String, boolean, ClassLoader)} rather than by a
 * {@code .class} literal: most operation classes are package-private, so a single
 * class in the {@code operations} package cannot refer to them directly. The names
 * are written from the very elements javac is compiling, so they always match the
 * classes they came from, but they are invisible to tools that strip unreferenced
 * classes, so this artifact must not be run through a minifier.
 *
 * <p>The table covers whatever javac was handed, which is not always the whole
 * source tree. Compile a subset and the table is regenerated for that subset alone
 * — recompiling one command on its own yields a table holding that one command.
 * Maven recompiles every source once any of them is stale, so a Maven build always
 * sees them all; an IDE compiling incrementally may not. Rebuild before trusting a
 * table that looks short.
 *
 * <p>This class is a build-time tool. javac cannot run a processor it is
 * compiling, so the build compiles this package first, on its own, into
 * {@code target/processor-classes} and passes that to the main compilation on
 * the processor path. The main compilation excludes this package, so neither it
 * nor JavaPoet ends up in the published artifact.
 */
@SupportedAnnotationTypes(CommandRegistryProcessor.REDIS_COMMAND)
public final class CommandRegistryProcessor extends AbstractProcessor {

    static final String REDIS_COMMAND = "com.github.fppt.jedismock.operations.RedisCommand";

    private static final String OPERATIONS_PACKAGE = "com.github.fppt.jedismock.operations";
    private static final String REDIS_OPERATION = OPERATIONS_PACKAGE + ".RedisOperation";
    private static final String REGISTRIES_CLASS = "CommandRegistries";
    private static final String COMMANDS_FIELD = "commands";
    private static final String LOAD_METHOD = "load";
    private static final String GENERATED_BY =
            "Generated by " + CommandRegistryProcessor.class.getName() + ". Do not edit.\n";

    /**
     * Commands by the {@code transactional} flag they were annotated with, then by
     * command name. Both orders are kept stable so that a rebuild produces
     * byte-identical sources.
     */
    private final Map<Boolean, SortedMap<String, Command>> commandsByFlag = new TreeMap<>();

    private boolean written;

    @Override
    public SourceVersion getSupportedSourceVersion() {
        return SourceVersion.latestSupported();
    }

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        if (roundEnv.processingOver()) {
            return false;
        }
        TypeElement redisCommand = processingEnv.getElementUtils().getTypeElement(REDIS_COMMAND);
        if (redisCommand == null) {
            return false;
        }
        for (Element element : roundEnv.getElementsAnnotatedWith(redisCommand)) {
            collect(element);
        }
        //Every operation is an original source file, so they have all been seen by the end of
        //the first round that reported any. Writing here rather than in the final round keeps
        //the generated sources subject to annotation processing themselves.
        if (!written && !commandsByFlag.isEmpty() && !annotations.isEmpty()) {
            written = true;
            write();
        }
        return false;
    }

    private void collect(Element element) {
        if (element.getKind() != ElementKind.CLASS) {
            error(element, "@RedisCommand may only annotate classes");
            return;
        }
        TypeElement type = (TypeElement) element;
        if (type.getModifiers().contains(Modifier.ABSTRACT)) {
            error(type, "@RedisCommand class must not be abstract");
            return;
        }
        if (type.getNestingKind().isNested() && !type.getModifiers().contains(Modifier.STATIC)) {
            error(type, "@RedisCommand class must be top level or a static nested class");
            return;
        }
        if (!isRedisOperation(type)) {
            error(type, "@RedisCommand class must implement " + REDIS_OPERATION);
            return;
        }
        String packageName = processingEnv.getElementUtils()
                .getPackageOf(type).getQualifiedName().toString();
        if (!packageName.equals(OPERATIONS_PACKAGE) && !packageName.startsWith(OPERATIONS_PACKAGE + ".")) {
            error(type, "@RedisCommand class must live in " + OPERATIONS_PACKAGE + " or a subpackage of it");
            return;
        }
        Map<String, AnnotationValue> values = redisCommandValues(type);
        if (values == null) {
            return;
        }
        String name = (String) values.get("value").getValue();
        Boolean transactional = (Boolean) values.get("transactional").getValue();
        String binaryName = processingEnv.getElementUtils().getBinaryName(type).toString();

        Command clash = commandsByFlag
                .computeIfAbsent(transactional, flag -> new TreeMap<>())
                .put(name, new Command(binaryName, type));
        if (clash != null) {
            //The table used to be built with Collectors.toMap, which threw on a duplicate key.
            //Generated puts would silently drop one of the two, so reject the clash here instead.
            error(type, "@RedisCommand(\"" + name + "\", transactional = " + transactional
                    + ") is already declared by " + clash.binaryName);
            error(clash.declaration, "@RedisCommand(\"" + name + "\", transactional = " + transactional
                    + ") is also declared by " + binaryName);
        }
    }

    /**
     * The {@code @RedisCommand} members of a command class, defaults filled in, by
     * member name. The annotation is read through mirrors rather than reflectively
     * because this processor is compiled on its own, without the library on its
     * classpath.
     */
    private Map<String, AnnotationValue> redisCommandValues(TypeElement type) {
        for (AnnotationMirror mirror : type.getAnnotationMirrors()) {
            TypeElement annotation = (TypeElement) mirror.getAnnotationType().asElement();
            if (!annotation.getQualifiedName().contentEquals(REDIS_COMMAND)) {
                continue;
            }
            Map<String, AnnotationValue> values = new HashMap<>();
            for (Map.Entry<? extends ExecutableElement, ? extends AnnotationValue> member
                    : processingEnv.getElementUtils().getElementValuesWithDefaults(mirror).entrySet()) {
                values.put(member.getKey().getSimpleName().toString(), member.getValue());
            }
            return values;
        }
        error(type, "@RedisCommand is not present on " + type.getQualifiedName());
        return null;
    }

    private boolean isRedisOperation(TypeElement type) {
        TypeElement operation = processingEnv.getElementUtils().getTypeElement(REDIS_OPERATION);
        if (operation == null) {
            //RedisOperation is compiled alongside the commands, so this only happens if the
            //annotation is used from outside the library, where we cannot check the bound.
            return true;
        }
        TypeMirror erasedOperation = processingEnv.getTypeUtils().erasure(operation.asType());
        TypeMirror erasedType = processingEnv.getTypeUtils().erasure(type.asType());
        return processingEnv.getTypeUtils().isAssignable(erasedType, erasedOperation);
    }

    private void write() {
        ClassName registries = ClassName.get(OPERATIONS_PACKAGE, REGISTRIES_CLASS);
        ClassName redisOperation = ClassName.bestGuess(REDIS_OPERATION);
        TypeName commandClass = ParameterizedTypeName.get(ClassName.get(Class.class),
                WildcardTypeName.subtypeOf(redisOperation));
        TypeName byName = ParameterizedTypeName.get(ClassName.get(Map.class),
                ClassName.get(String.class), commandClass);
        TypeName byFlag = ParameterizedTypeName.get(ClassName.get(Map.class),
                ClassName.get(Boolean.class), byName);

        TypeSpec spec = TypeSpec.classBuilder(registries)
                .addJavadoc("Every operation class in the library, by the {@code transactional} flag of "
                        + "its {@code $L} annotation and then by command name.\n\n"
                        + "<p>Internal API, the table {@link CommandFactory} looks commands up in. It is "
                        + "written at compile time from the annotations of the classes javac was handed, "
                        + "so an incremental build that recompiles only some of them leaves a table for "
                        + "only those. Rebuild before trusting a table that looks short.\n", REDIS_COMMAND)
                .addJavadoc("\n<p>$L", GENERATED_BY)
                .addModifiers(Modifier.FINAL, Modifier.PUBLIC)
                .addField(FieldSpec.builder(byFlag, COMMANDS_FIELD,
                        Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL).build())
                .addStaticBlock(table(byName, byFlag))
                .addMethod(MethodSpec.constructorBuilder().addModifiers(Modifier.PRIVATE).build())
                .addMethod(loadMethod(registries, redisOperation, commandClass))
                .build();

        try {
            JavaFile.builder(OPERATIONS_PACKAGE, spec)
                    .skipJavaLangImports(true)
                    .indent("    ")
                    .build()
                    .writeTo(processingEnv.getFiler());
        } catch (IOException e) {
            throw new UncheckedIOException("Cannot write " + OPERATIONS_PACKAGE + "." + spec.name(), e);
        }
    }

    private CodeBlock table(TypeName byName, TypeName byFlag) {
        CodeBlock.Builder table = CodeBlock.builder();
        for (boolean flag : new boolean[]{false, true}) {
            table.addStatement("$T $L = new $T<>()", byName, variable(flag), HashMap.class);
            for (Map.Entry<String, Command> command : commands(flag).entrySet()) {
                table.addStatement("$L.put($S, $L($S))", variable(flag), command.getKey(),
                        LOAD_METHOD, command.getValue().binaryName);
            }
        }
        table.addStatement("$T byFlag = new $T<>()", byFlag, HashMap.class);
        for (boolean flag : new boolean[]{false, true}) {
            table.addStatement("byFlag.put($T.$L, $T.unmodifiableMap($L))",
                    Boolean.class, flag ? "TRUE" : "FALSE", Collections.class, variable(flag));
        }
        table.addStatement("$L = $T.unmodifiableMap(byFlag)", COMMANDS_FIELD, Collections.class);
        return table.build();
    }

    private MethodSpec loadMethod(ClassName registries, ClassName redisOperation, TypeName commandClass) {
        return MethodSpec.methodBuilder(LOAD_METHOD)
                .addJavadoc("Resolves an operation class by binary name.\n\n"
                        + "@param binaryName the binary name of an operation class in this library\n"
                        + "@return the operation class\n")
                .addModifiers(Modifier.PRIVATE, Modifier.STATIC)
                .returns(commandClass)
                .addParameter(String.class, "binaryName")
                .beginControlFlow("try")
                .addStatement("return $T.forName(binaryName, false, $T.class.getClassLoader())"
                        + ".asSubclass($T.class)", Class.class, registries, redisOperation)
                .nextControlFlow("catch ($T e)", ClassNotFoundException.class)
                .addStatement("throw new $T($S + binaryName, e)",
                        IllegalStateException.class, "Cannot load command class ")
                .endControlFlow()
                .build();
    }

    private SortedMap<String, Command> commands(boolean transactional) {
        SortedMap<String, Command> byName = commandsByFlag.get(transactional);
        return byName == null ? Collections.<String, Command>emptySortedMap() : byName;
    }

    private String variable(boolean transactional) {
        return transactional ? "transactional" : "nonTransactional";
    }

    private void error(Element element, String message) {
        processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR, message, element);
    }

    /**
     * An operation class, kept with the element that declared it so that a
     * duplicate command name can be reported against its source.
     */
    private static final class Command {
        private final String binaryName;
        private final Element declaration;

        Command(String binaryName, Element declaration) {
            this.binaryName = binaryName;
            this.declaration = declaration;
        }
    }
}
