package com.github.fppt.jedismock.operations;

import java.util.List;

/**
 * Supplies the {@link RedisCommand} classes declared in one operations
 * subpackage.
 *
 * <p>Internal API. Implementations are generated by
 * {@code scripts/generate-command-registries.sh} — one per subpackage — and
 * found by {@link CommandFactory} through {@link java.util.ServiceLoader}, so
 * that operations can be enumerated without scanning the classpath. Most
 * operation classes are package-private and can only be named from inside
 * their own package, which is why there is one registry per package rather
 * than one central list.
 */
public interface CommandRegistry {

    /**
     * The operation classes declared in this registry's package.
     */
    List<Class<? extends RedisOperation>> commands();
}
