package com.github.fppt.jedismock.processor;

import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.CodeBlock;
import com.palantir.javapoet.JavaFile;
import com.palantir.javapoet.MethodSpec;
import com.palantir.javapoet.ParameterizedTypeName;
import com.palantir.javapoet.TypeName;
import com.palantir.javapoet.TypeSpec;
import com.palantir.javapoet.WildcardTypeName;

import javax.annotation.processing.AbstractProcessor;
import javax.annotation.processing.RoundEnvironment;
import javax.annotation.processing.SupportedAnnotationTypes;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.Element;
import javax.lang.model.element.ElementKind;
import javax.lang.model.element.Modifier;
import javax.lang.model.element.TypeElement;
import javax.lang.model.type.TypeMirror;
import javax.tools.Diagnostic;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.SortedSet;
import java.util.TreeMap;
import java.util.TreeSet;

/**
 * Generates, at compile time, the lookup tables that
 * {@code CommandFactory} uses to find the operation class behind a Redis
 * command name.
 *
 * <p>Every class carrying {@code @RedisCommand} is reported to this processor
 * by javac, so the commands are located by the compiler rather than by
 * scanning the classpath at start-up. For each operations subpackage the
 * processor emits a public {@code <Package>Commands} class listing that
 * package's operation classes, and it ties them together with a
 * package-private {@code CommandRegistries} class in
 * {@code com.github.fppt.jedismock.operations}. There is one registry per
 * package because most operation classes are package-private and can only be
 * named from inside their own package.
 *
 * <p>The generated code cannot go stale: it is rebuilt from the annotations on
 * every compilation, and a command that is added without being picked up here
 * would have to have lost its annotation to begin with.
 *
 * <p>This class is a build-time tool. It is compiled from {@code src/processor/java}
 * into {@code target/processor-classes} and passed to javac on the processor
 * path, so neither it nor JavaPoet ends up in the published artifact.
 */
@SupportedAnnotationTypes(CommandRegistryProcessor.REDIS_COMMAND)
public final class CommandRegistryProcessor extends AbstractProcessor {

    static final String REDIS_COMMAND = "com.github.fppt.jedismock.operations.RedisCommand";

    private static final String OPERATIONS_PACKAGE = "com.github.fppt.jedismock.operations";
    private static final String REDIS_OPERATION = OPERATIONS_PACKAGE + ".RedisOperation";
    private static final String REGISTRIES_CLASS = "CommandRegistries";
    private static final String REGISTRY_SUFFIX = "Commands";
    private static final String GENERATED_BY =
            "Generated by " + CommandRegistryProcessor.class.getName() + ". Do not edit.\n";

    /**
     * Operation classes keyed by the package that declares them, both orders
     * kept stable so that a rebuild produces byte-identical sources.
     */
    private final Map<String, SortedSet<ClassName>> commandsByPackage = new TreeMap<>();

    private boolean written;

    @Override
    public SourceVersion getSupportedSourceVersion() {
        return SourceVersion.latestSupported();
    }

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        if (roundEnv.processingOver()) {
            return false;
        }
        TypeElement redisCommand = processingEnv.getElementUtils().getTypeElement(REDIS_COMMAND);
        if (redisCommand == null) {
            return false;
        }
        for (Element element : roundEnv.getElementsAnnotatedWith(redisCommand)) {
            collect(element);
        }
        //Every operation is an original source file, so they have all been seen by the end of
        //the first round that reported any. Writing here rather than in the final round keeps
        //the generated sources subject to annotation processing themselves.
        if (!written && !commandsByPackage.isEmpty() && !annotations.isEmpty()) {
            written = true;
            write();
        }
        return false;
    }

    private void collect(Element element) {
        if (element.getKind() != ElementKind.CLASS) {
            error(element, "@RedisCommand may only annotate classes");
            return;
        }
        TypeElement type = (TypeElement) element;
        if (type.getModifiers().contains(Modifier.ABSTRACT)) {
            error(type, "@RedisCommand class must not be abstract");
            return;
        }
        if (type.getNestingKind().isNested() && !type.getModifiers().contains(Modifier.STATIC)) {
            error(type, "@RedisCommand class must be top level or a static nested class");
            return;
        }
        if (!isRedisOperation(type)) {
            error(type, "@RedisCommand class must implement " + REDIS_OPERATION);
            return;
        }
        String packageName = processingEnv.getElementUtils()
                .getPackageOf(type).getQualifiedName().toString();
        if (!packageName.equals(OPERATIONS_PACKAGE) && !packageName.startsWith(OPERATIONS_PACKAGE + ".")) {
            error(type, "@RedisCommand class must live in " + OPERATIONS_PACKAGE + " or a subpackage of it");
            return;
        }
        commandsByPackage.computeIfAbsent(packageName, p -> new TreeSet<>(
                        (a, b) -> a.canonicalName().compareTo(b.canonicalName())))
                .add(ClassName.get(type));
    }

    private boolean isRedisOperation(TypeElement type) {
        TypeElement operation = processingEnv.getElementUtils().getTypeElement(REDIS_OPERATION);
        if (operation == null) {
            //RedisOperation is compiled alongside the commands, so this only happens if the
            //annotation is used from outside the library, where we cannot check the bound.
            return true;
        }
        TypeMirror erasedOperation = processingEnv.getTypeUtils().erasure(operation.asType());
        TypeMirror erasedType = processingEnv.getTypeUtils().erasure(type.asType());
        return processingEnv.getTypeUtils().isAssignable(erasedType, erasedOperation);
    }

    private void write() {
        TypeName commandClass = ParameterizedTypeName.get(ClassName.get(Class.class),
                WildcardTypeName.subtypeOf(ClassName.bestGuess(REDIS_OPERATION)));
        TypeName commandList = ParameterizedTypeName.get(ClassName.get(List.class), commandClass);

        List<ClassName> registries = new ArrayList<>();
        for (Map.Entry<String, SortedSet<ClassName>> entry : commandsByPackage.entrySet()) {
            ClassName registry = ClassName.get(entry.getKey(), registryName(entry.getKey()));
            registries.add(registry);
            emit(entry.getKey(), registryClass(registry, entry.getValue(), commandList));
        }
        emit(OPERATIONS_PACKAGE, registriesClass(registries, commandClass, commandList));
    }

    private TypeSpec.Builder registryClass(ClassName registry, SortedSet<ClassName> commands, TypeName commandList) {
        CodeBlock.Builder body = CodeBlock.builder().add("return $T.asList(", Arrays.class);
        boolean first = true;
        for (ClassName command : commands) {
            body.add(first ? "\n$T.class" : ",\n$T.class", command);
            first = false;
        }
        body.add(")");

        return TypeSpec.classBuilder(registry)
                .addJavadoc("The {@link $L} classes declared in this package.\n\n"
                                + "<p>Internal API. It exists so that {@code $L.CommandFactory} can look up "
                                + "operations without scanning the classpath; most operation classes are "
                                + "package-private and can only be named from inside their own package.\n",
                        REDIS_COMMAND, OPERATIONS_PACKAGE)
                .addJavadoc("\n<p>$L", GENERATED_BY)
                .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
                .addMethod(MethodSpec.constructorBuilder().addModifiers(Modifier.PRIVATE).build())
                .addMethod(MethodSpec.methodBuilder("commands")
                        .addJavadoc("The operation classes declared in this package.\n\n"
                                + "@return the operation classes, in a stable order\n")
                        .addModifiers(Modifier.PUBLIC, Modifier.STATIC)
                        .returns(commandList)
                        .addStatement(body.build())
                        .build());
    }

    private TypeSpec.Builder registriesClass(List<ClassName> registries, TypeName commandClass, TypeName commandList) {
        MethodSpec.Builder all = MethodSpec.methodBuilder("all")
                .addJavadoc("Every operation class in the library.\n\n"
                        + "@return the operation classes, in a stable order\n")
                .addModifiers(Modifier.STATIC)
                .returns(commandList)
                .addStatement("$T<$T> commands = new $T<>()", List.class, commandClass, ArrayList.class);
        for (ClassName registry : registries) {
            all.addStatement("commands.addAll($T.commands())", registry);
        }
        all.addStatement("return commands");

        return TypeSpec.classBuilder(ClassName.get(OPERATIONS_PACKAGE, REGISTRIES_CLASS))
                .addJavadoc("The per-package command registries, gathered into one list.\n\n"
                        + "<p>Internal API, the entry point {@link CommandFactory} builds its lookup "
                        + "tables from.\n")
                .addJavadoc("\n<p>$L", GENERATED_BY)
                .addModifiers(Modifier.FINAL)
                .addMethod(MethodSpec.constructorBuilder().addModifiers(Modifier.PRIVATE).build())
                .addMethod(all.build());
    }

    private void emit(String packageName, TypeSpec.Builder type) {
        TypeSpec spec = type.build();
        try {
            JavaFile.builder(packageName, spec)
                    .skipJavaLangImports(true)
                    .indent("    ")
                    .build()
                    .writeTo(processingEnv.getFiler());
        } catch (IOException e) {
            throw new UncheckedIOException("Cannot write " + packageName + "." + spec.name(), e);
        }
    }

    private String registryName(String packageName) {
        String relative = packageName.equals(OPERATIONS_PACKAGE)
                ? "operations"
                : packageName.substring(OPERATIONS_PACKAGE.length() + 1);
        StringBuilder name = new StringBuilder();
        for (String segment : relative.split("\\.")) {
            name.append(Character.toUpperCase(segment.charAt(0))).append(segment.substring(1));
        }
        return name.append(REGISTRY_SUFFIX).toString();
    }

    private void error(Element element, String message) {
        processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR, message, element);
    }
}
