package com.github.fppt.jedismock.operations.transactions;

import com.github.fppt.jedismock.operations.CommandRegistry;
import com.github.fppt.jedismock.operations.RedisOperation;

import java.util.Arrays;
import java.util.List;

/**
 * Registry of the {@link com.github.fppt.jedismock.operations.RedisCommand}
 * classes declared in this package.
 *
 * <p>Internal API. It exists so that
 * {@link com.github.fppt.jedismock.operations.CommandFactory} can enumerate
 * operations without scanning the classpath. Most operation classes are
 * package-private and can only be named from inside their own package, which
 * is why there is one registry per package rather than one central list.
 *
 * <p>Generated by scripts/generate-command-registries.sh, which also lists
 * this class in META-INF/services so that {@link
 * com.github.fppt.jedismock.operations.CommandRegistry} finds it. Entries may
 * also be added by hand; {@code CommandRegistryCompletenessTest} tells you
 * exactly what is missing if you forget.
 */
public final class TransactionsCommands implements CommandRegistry {

    @Override
    public List<Class<? extends RedisOperation>> commands() {
        return Arrays.asList(
                Discard.class,
                Exec.class,
                Multi.class,
                Unwatch.class,
                Watch.class);
    }
}
