#!/usr/bin/env bash
# Generates one <Pkg>Commands registry per operations subpackage from the
# @RedisCommand annotations, plus the META-INF/services file through which
# CommandFactory discovers them. Run from the repository root. Idempotent:
# re-running it on an unchanged tree produces no diff.
#
# This is the single command that answers every "how do I register a command"
# question, including adding a command in a brand-new subpackage — CommandFactory
# itself is never edited, because registries reach it via ServiceLoader.
#
# Pass --check to verify instead of write: the registries and service file are
# regenerated into a scratch directory and compared against the working tree,
# exiting non-zero with a diff if they differ. `mvn verify` runs this mode.
#
# Portable across GNU (Linux) and BSD (macOS) userlands: it deliberately avoids
# `mapfile` (bash 4+, absent from macOS's stock bash 3.2), `xargs -r` (a GNU
# extension BSD xargs doesn't have), and GNU sed's `\U` (not a BSD sed escape).
# Capitalization is done with `awk`'s `toupper`/`substr`, which behave the same
# under GNU awk, BSD awk and mawk.
set -euo pipefail

# Force a fixed sort order regardless of the invoking shell's locale, and
# case-fold it (`-f`, POSIX, supported by both GNU and BSD sort) so the order
# matches the case-insensitive-looking listing style already in the tree (e.g.
# HPersist before HPExpire). Without LC_ALL=C, `sort -f` on a mixed-case class
# name can still order entries differently between an en_US.UTF-8 machine and
# a "C" one, turning a locale difference into a spurious registry diff.
export LC_ALL=C

CHECK_ONLY=0
if [ "${1:-}" = "--check" ]; then
    CHECK_ONLY=1
elif [ "$#" -gt 0 ]; then
    echo "usage: $0 [--check]" >&2
    exit 2
fi

OPS_DIR="src/main/java/com/github/fppt/jedismock/operations"
BASE_PKG="com.github.fppt.jedismock.operations"
SERVICES_FILE="src/main/resources/META-INF/services/$BASE_PKG.CommandRegistry"

# In --check mode everything is written under a scratch root and diffed against
# the working tree, so the sources are never touched.
if [ "$CHECK_ONLY" -eq 1 ]; then
    scratch="$(mktemp -d "${TMPDIR:-/tmp}/jedismock-cmdreg-check.XXXXXXXX")"
    trap 'rm -rf "$scratch"' EXIT
    out_root="$scratch"
    mkdir -p "$out_root/$OPS_DIR" "$out_root/$(dirname "$SERVICES_FILE")"
else
    out_root="."
fi

capitalize() {
    # Portable "uppercase the first letter of every line" - no GNU sed \U needed.
    awk '{ print toupper(substr($0, 1, 1)) substr($0, 2) }'
}

# An explicit template (as opposed to a bare `mktemp` call) is required for
# portability: BSD/macOS mktemp has no default template the way GNU's does.
services_tmp="$(mktemp "${TMPDIR:-/tmp}/jedismock-cmdreg.XXXXXXXX")"
trap 'rm -f "$services_tmp"; [ "$CHECK_ONLY" -eq 1 ] && rm -rf "$scratch"' EXIT

# Iterate via process substitution (not a pipe) so the loop body runs in the
# current shell and can accumulate services_tmp across iterations.
while IFS= read -r rel; do
    dir="$OPS_DIR/$rel"

    classes=()
    while IFS= read -r file; do
        [ -n "$file" ] && classes+=("$(basename "$file" .java)")
    done < <(grep -l '^@RedisCommand' "$dir"/*.java 2>/dev/null | sort -f)
    [ "${#classes[@]}" -eq 0 ] && continue

    pkg="$BASE_PKG.$(echo "$rel" | tr '/' '.')"
    # bitmaps -> Bitmaps ; hashes/expiration -> HashesExpiration
    name="$(echo "$rel" | tr '/' '\n' | capitalize | tr -d '\n')Commands"
    out="$out_root/$dir/$name.java"
    mkdir -p "$(dirname "$out")"

    {
        echo "package $pkg;"
        echo
        echo "import com.github.fppt.jedismock.operations.CommandRegistry;"
        echo "import com.github.fppt.jedismock.operations.RedisOperation;"
        echo
        echo "import java.util.Arrays;"
        echo "import java.util.List;"
        echo
        echo "/**"
        echo " * Registry of the {@link com.github.fppt.jedismock.operations.RedisCommand}"
        echo " * classes declared in this package."
        echo " *"
        echo " * <p>Internal API. It exists so that"
        echo " * {@link com.github.fppt.jedismock.operations.CommandFactory} can enumerate"
        echo " * operations without scanning the classpath. Most operation classes are"
        echo " * package-private and can only be named from inside their own package, which"
        echo " * is why there is one registry per package rather than one central list."
        echo " *"
        echo " * <p>Generated by scripts/generate-command-registries.sh, which also lists"
        echo " * this class in META-INF/services so that {@link"
        echo " * com.github.fppt.jedismock.operations.CommandRegistry} finds it. Entries may"
        echo " * also be added by hand; {@code CommandRegistryCompletenessTest} tells you"
        echo " * exactly what is missing if you forget."
        echo " */"
        echo "public final class $name implements CommandRegistry {"
        echo
        echo "    @Override"
        echo "    public List<Class<? extends RedisOperation>> commands() {"
        echo "        return Arrays.asList("
        for i in "${!classes[@]}"; do
            if [ "$i" -eq $(( ${#classes[@]} - 1 )) ]; then
                echo "                ${classes[$i]}.class);"
            else
                echo "                ${classes[$i]}.class,"
            fi
        done
        echo "    }"
        echo "}"
    } > "$out"
    [ "$CHECK_ONLY" -eq 1 ] || echo "wrote $out (${#classes[@]} commands)"

    echo "$pkg.$name" >> "$services_tmp"
done < <(find "$OPS_DIR" -mindepth 1 -type d | sed "s|^$OPS_DIR/||" | sort)

# --- Service file ----------------------------------------------------------
#
# CommandFactory loads these through ServiceLoader, so a registry missing from
# this list is simply never consulted and its commands report as unsupported.
{
    echo "# Generated by scripts/generate-command-registries.sh - do not edit by hand."
    echo "# Registries of the @RedisCommand classes of each operations subpackage,"
    echo "# loaded by CommandFactory via ServiceLoader."
    sort < "$services_tmp"
} > "$out_root/$SERVICES_FILE"
[ "$CHECK_ONLY" -eq 1 ] || echo "wrote $SERVICES_FILE ($(wc -l < "$services_tmp" | tr -d ' ') registries)"

if [ "$CHECK_ONLY" -eq 1 ]; then
    status=0
    # Every file the generator produced must match the committed one...
    while IFS= read -r generated; do
        actual="${generated#"$out_root"/}"
        if ! diff -u "$actual" "$generated" >/dev/null 2>&1; then
            echo "stale: $actual" >&2
            diff -u "$actual" "$generated" >&2 || true
            status=1
        fi
    done < <(find "$out_root/$OPS_DIR" -name '*Commands.java'; echo "$out_root/$SERVICES_FILE")
    # ...and no registry may linger for a package the generator no longer emits
    # (a subpackage whose last @RedisCommand class was removed or moved).
    while IFS= read -r committed; do
        if [ ! -f "$out_root/$committed" ]; then
            echo "orphaned: $committed has no @RedisCommand classes left to register" >&2
            status=1
        fi
    done < <(find "$OPS_DIR" -name '*Commands.java')
    if [ "$status" -ne 0 ]; then
        echo >&2
        echo "The command registries are out of date. Run" \
            "./scripts/generate-command-registries.sh and commit the result." >&2
        exit 1
    fi
    echo "command registries are up to date"
fi
